const charDescriptions = [
    "NUL (Null)", "☺ - SOH (Start of Heading)", "☻ - STX (Start of Text)", "♥ - ETX (End of Text)",
    "♦ - EOT (End of Transmission)", "♣ - ENQ (Enquiry)", "♠ - ACK (Acknowledgement)", "• - BEL (Bell)",
    "◘ - BS (Backspace)", "○ - HT (Horizontal Tab)", "◙ - LF (Line Feed)", "♂ - VT (Vertical Tab)",
    "♀ - FF (Form Feed)", "♪ - CR (Carriage Return)", "♫ - SO (Shift Out)", "☼ - SI (Shift In)",
    "► - DLE (Data Link Escape)", "◄ - DC1 (Device Control 1)", "↕ - DC2 (Device Control 2)", "‼ - DC3 (Device Control 3)",
    "¶ - DC4 (Device Control 4)", "§ - NAK (Negative Acknowledgement)", "▬ - SYN (Synchronous Idle)", "↨ - ETB (End of Transmission Block)",
    "↑ - CAN (Cancel)", "↓ - EM (End of Medium)", "→ - SUB (Substitute)", "← - ESC (Escape)",
    "∟ - FS (File Separator)", "↔ - GS (Group Separator)", "▲ - RS (Record Separator)", "▼ - US (Unit Separator)",
    "Space", "! - Exclamation mark", "\" - Quotation mark", "# - Number sign",
    "$ - Dollar sign", "% - Percent sign", "& - Ampersand", "' - Apostrophe",
    "( - Left parenthesis", ") - Right parenthesis", "* - Asterisk", "+ - Plus sign",
    ", - Comma", "- - Hyphen-minus", ". - Full stop", "/ - Solidus",
    "0 - Digit Zero", "1 - Digit One", "2 - Digit Two", "3 - Digit Three",
    "4 - Digit Four", "5 - Digit Five", "6 - Digit Six", "7 - Digit Seven",
    "8 - Digit Eight", "9 - Digit Nine", ": - Colon", "; - Semicolon",
    "< - Less-than sign", "= - Equals sign", "> - Greater-than sign", "? - Question mark",
    "@ - Commercial at", "A - Latin Capital letter A", "B - Latin Capital letter B", "C - Latin Capital letter C",
    "D - Latin Capital letter D", "E - Latin Capital letter E", "F - Latin Capital letter F", "G - Latin Capital letter G",
    "H - Latin Capital letter H", "I - Latin Capital letter I", "J - Latin Capital letter J", "K - Latin Capital letter K",
    "L - Latin Capital letter L", "M - Latin Capital letter M", "N - Latin Capital letter N", "O - Latin Capital letter O",
    "P - Latin Capital letter P", "Q - Latin Capital letter Q", "R - Latin Capital letter R", "S - Latin Capital letter S",
    "T - Latin Capital letter T", "U - Latin Capital letter U", "V - Latin Capital letter V", "W - Latin Capital letter W",
    "X - Latin Capital letter X", "Y - Latin Capital letter Y", "Z - Latin Capital letter Z", "[ - Left square bracket",
    "\\ - Reverse solidus", "] - Right square bracket", "^ - Circumflex accent", "_ - Low line",
    "` - Grave accent", "a - Latin Small letter a", "b - Latin Small letter b", "c - Latin Small letter c",
    "d - Latin Small letter d", "e - Latin Small letter e", "f - Latin Small letter f", "g - Latin Small letter g",
    "h - Latin Small letter h", "i - Latin Small letter i", "j - Latin Small letter j", "k - Latin Small letter k",
    "l - Latin Small letter l", "m - Latin Small letter m", "n - Latin Small letter n", "o - Latin Small letter o",
    "p - Latin Small letter p", "q - Latin Small letter q", "r - Latin Small letter r", "s - Latin Small letter s",
    "t - Latin Small letter t", "u - Latin Small letter u", "v - Latin Small letter v", "w - Latin Small letter w",
    "x - Latin Small letter x", "y - Latin Small letter y", "z - Latin Small letter z", "{ - Left curly bracket",
    "| - Vertical line", "} - Right curly bracket", "~ - Tilde", "⌂ - DEL (Delete)",
    "Ç - Latin Capital letter C with cedilla", "ü - Latin Small letter u with diaeresis", "é - Latin Small letter e with acute", "â - Latin Small letter a with circumflex",
    "ä - Latin Small letter a with diaeresis", "à - Latin Small letter a with grave", "å - Latin Small letter a with ring above", "ç - Latin Small letter c with cedilla",
    "ê - Latin Small letter e with circumflex", "ë - Latin Small letter e with diaeresis", "è - Latin Small letter e with grave", "ï - Latin Small letter i with diaeresis",
    "î - Latin Small letter i with circumflex", "ì - Latin Small letter i with grave", "Ä - Latin Capital letter A with diaeresis", "Å - Latin Capital letter A with ring above",
    "É - Latin Capital letter E with acute", "æ - Latin Small letter ae", "Æ - Latin Capital letter AE", "ô - Latin Small letter o with circumflex",
    "ö - Latin Small letter o with diaeresis", "ò - Latin Small letter o with grave", "û - Latin Small letter u with circumflex", "ù - Latin Small letter u with grave",
    "ÿ - Latin Small letter y with diaeresis", "Ö - Latin Capital letter O with diaeresis", "Ü - Latin Capital letter U with diaeresis", "¢ - Cent sign",
    "£ - Pound sign", "¥ - Yen sign", "₧ - Peseta sign", "ƒ - Latin Small letter f with hook",
    "á - Latin Small letter a with acute", "í - Latin Small letter i with acute", "ó - Latin Small letter o with acute", "ú - Latin Small letter u with acute",
    "ñ - Latin Small letter n with tilde", "Ñ - Latin Capital letter N with tilde", "ª - Feminine ordinal indicator", "º - Masculine ordinal indicator",
    "¿ - Inverted question mark", "⌐ - Reversed not sign", "¬ - Not sign", "½ - Vulgar fraction one half",
    "¼ - Vulgar fraction one quarter", "¡ - Inverted exclamation mark", "« - Left-pointing double angle quotation mark", "» - Right-pointing double angle quotation mark",
    "░ - Light shade", "▒ - Medium shade", "▓ - Dark shade", "│ - Box drawings light vertical",
    "┤ - Box drawings light vertical and left", "╡ - Box drawings vertical light and left double", "╢ - Box drawings vertical double and left light", "╖ - Box drawings down double and left light",
    "╕ - Box drawings down light and left double", "╣ - Box drawings vertical double and left double", "║ - Box drawings double vertical", "╗ - Box drawings double down and left",
    "╝ - Box drawings double up and left", "╜ - Box drawings up double and left light", "╛ - Box drawings up light and left double", "┐ - Box drawings light down and left",
    "└ - Box drawings light up and right", "┴ - Box drawings light up and horizontal", "┬ - Box drawings light down and horizontal", "├ - Box drawings light vertical and right",
    "─ - Box drawings light horizontal", "┼ - Box drawings light vertical and horizontal", "╞ - Box drawings vertical light and right double", "╟ - Box drawings vertical double and right light",
    "╚ - Box drawings double up and right", "╔ - Box drawings double down and right", "╩ - Box drawings double up and horizontal", "╦ - Box drawings double down and horizontal",
    "╠ - Box drawings double vertical and right", "═ - Box drawings double horizontal", "╬ - Box drawings double vertical and horizontal", "╧ - Box drawings up light and horizontal double",
    "╨ - Box drawings up double and horizontal light", "╤ - Box drawings down light and horizontal double", "╥ - Box drawings down double and horizontal light", "╙ - Box drawings up double and right light",
    "╘ - Box drawings up light and right double", "╒ - Box drawings down light and right double", "╓ - Box drawings down double and right light", "╫ - Box drawings vertical double and horizontal light",
    "╪ - Box drawings vertical light and horizontal double", "┘ - Box drawings light up and left", "┌ - Box drawings light down and right", "█ - Full block",
    "▄ - Lower half block", "▌ - Left half block", "▐ - Right half block", "▀ - Upper half block",
    "α - Greek Small letter alpha", "ß - Latin Small letter sharp s", "Γ - Greek Capital letter gamma", "π - Greek Small letter pi",
    "Σ - Greek Capital letter sigma", "σ - Greek Small letter sigma", "µ - Micro sign", "τ - Greek Small letter tau",
    "Φ - Greek Capital letter phi", "Θ - Greek Capital letter theta", "Ω - Greek Capital letter omega", "δ - Greek Small letter delta",
    "∞ - Infinity", "φ - Greek Small letter phi", "ε - Greek Small letter epsilon", "∩ - Intersection",
    "≡ - Identical to", "± - Plus-minus sign", "≥ - Greater-than or equal to", "≤ - Less-than or equal to",
    "⌠ - Top half integral", "⌡ - Bottom half integral", "÷ - Division sign", "≈ - Almost equal to",
    "° - Degree sign", "∙ - Bullet operator", "· - Middle dot", "√ - Square root",
    "ⁿ - Superscript Latin Small letter n", "² - Superscript two", "■ - Black small square", "Non-breaking space"
];